# Generated by Django 4.0.4 on 2022-04-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_geeksmodel_img_alter_geeksmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='img',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
