# Generated by Django 4.0.4 on 2022-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_geeksmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/allien.png', null=True, upload_to='images/'),
        ),
    ]
